import type { PaperMetadata } from "./types.js";

// The `paperbaker/README.md` guide the CLI generates and keeps up to date, and —
// the single source of truth — the CLI documentation rendered on the website
// (apps/web renders `generateProjectReadme([])`). The CLI WRITES it into a
// project (with that project's papers appended); the web PREVIEWS it with no
// papers. Keeping one generator means the published docs and the in-repo guide
// can never drift. The companion short pointer injected into a repo's root
// AGENTS.md/CLAUDE.md lives in agent-brief.ts.

// Layout of the visible project dir. Private to this module — the CLI has its
// own copies in config.ts / helpers/sources.ts for filesystem work; these exist
// only so the generated text is correct.
const PROJECT_DIR = "paperbaker";
const SOURCES_REL = `${PROJECT_DIR}/sources`;

/** Filename of the full per-project guide, inside the visible paperbaker/ dir. */
export const PROJECT_README = "README.md";

/** Directory name a paper's tex source is extracted into, under sources/. */
export function sourceDirName(paper: PaperMetadata): string {
  return paper.source.type === "arxiv"
    ? `arxiv-${paper.source.id}`
    : paper.paperId.replace(":", "-");
}

/**
 * The Paper Baker CLI guide, rendered as markdown. With papers, the project's
 * own list is appended (the in-repo `paperbaker/README.md`); with none, it's the
 * generic reference shown on the website's CLI docs page.
 */
export function generateProjectReadme(papers: PaperMetadata[]): string {
  const lines: string[] = [
    "# Paper Baker CLI",
    "",
    "`pb` downloads the LaTeX source of papers from arXiv into your repository and keeps",
    "generated metadata, a bibliography, and this guide alongside it. Everything lands in a",
    "single `paperbaker/` directory as plain text, so a coding agent can read and search the",
    "papers with the same tools it uses for code.",
    "",
    "The CLI works offline; sign in only to sync with the web app.",
    "",
    "## Install",
    "",
    "```sh",
    "curl -LsSf https://paper-baker.web.app/install.sh | sh",
    "```",
    "",
    "On Windows, run `irm https://paper-baker.web.app/install.ps1 | iex` in PowerShell. This",
    "installs the self-contained `pb` binary into `~/.local/bin`.",
    "",
    "## Reading papers",
    "",
    "The papers are plain `.tex` files under `paperbaker/sources/<paper-id>/`. Read and search",
    "them the way you read code — open the files directly, and grep across them:",
    "",
    "```sh",
    'rg "scaled dot-product" paperbaker/sources/',
    "```",
    "",
    "A paper's source is usually split across several files: the entry `.tex` (the one with",
    "`\\documentclass`) pulls in sections with `\\input{...}` / `\\include{...}`. Follow those",
    "like imports — the referenced files sit in the same directory. Prefer the `.tex` source",
    "over any PDF: equations, tables, and notation only survive in the source.",
    "",
    "The commands below are conveniences on top of those files.",
    "",
    "## Commands",
    "",
    "Run `pb --help` or `pb <command> --help` for usage. Most read commands accept `--json`;",
    "login is optional and only required for syncing.",
    "",
    "Once a project is bound to the server, most commands reconcile with it automatically when",
    "they finish — adding, removing, reading, or listing all trigger a quiet background sync — so",
    "you rarely need to run `pb sync` by hand. The automatic pass only touches **already-bound**",
    "projects and never publishes a local-only one.",
    "",
    "### Papers",
    "",
    "#### `pb search <query>`",
    "",
    "Search arXiv. Throttled to arXiv's rate limits.",
    "",
    "| Option | Description |",
    "| --- | --- |",
    "| `-n, --max-results <n>` | Max results (default `10`) |",
    "| `--json` | Output results as JSON |",
    "",
    "#### `pb add <id-or-url...>`",
    "",
    "Resolve one or more arXiv IDs or URLs, add the papers, and download their `.tex` sources",
    "into `paperbaker/sources/`. Regenerates `refs.bib` and this guide, and mirrors to the",
    "server when the project is synced. Already-present papers are skipped; the command exits",
    "non-zero if any id couldn't be added.",
    "",
    "```sh",
    "pb add 1706.03762 2005.14165 https://arxiv.org/abs/1810.04805",
    "```",
    "",
    "#### `pb remove <paper-id...>`",
    "",
    "Remove one or more papers and delete their source directories.",
    "",
    "#### `pb list`",
    "",
    "List the papers in the current project.",
    "",
    "#### `pb show <paper-id>`",
    "",
    "Print detailed metadata for one paper.",
    "",
    "### Reading",
    "",
    "#### `pb read <paper-id>`",
    "",
    "Print a paper's full LaTeX source to stdout — every `.tex` file, each under its",
    "source-relative path header, with `\\input`/`\\include` left unexpanded (follow them to the",
    "sibling files). For a one-file paper this is just that file.",
    "",
    "#### `pb context`",
    "",
    "Print the concatenated tex bodies and figure list for every paper — one blob for an",
    "agent's context window.",
    "",
    "#### `pb bib`",
    "",
    "Regenerate `refs.bib` and print it to stdout.",
    "",
    "### Projects",
    "",
    "A project binds a directory to a set of papers.",
    "",
    "#### `pb project create [name]`",
    "",
    "Scaffold `paperbaker/` and create the project. Publishes to the server when logged in, else",
    "stays local until the first `pb sync`. Name defaults to the directory name.",
    "",
    "| Option | Description |",
    "| --- | --- |",
    "| `--no-brief` | Don't add the brief to the root `AGENTS.md`/`CLAUDE.md` |",
    "",
    "#### `pb project bind <id|handle/id>`",
    "",
    "Bind the current directory to an existing remote project. Use a bare `id` for one of",
    "your own projects, or `handle/id` for another owner's (once it's shared with you).",
    "",
    "| Option | Description |",
    "| --- | --- |",
    "| `--merge` | On drift, union local and remote papers |",
    "| `--replace-local` | On drift, take the remote state |",
    "| `--no-brief` | Don't add the brief to the root `AGENTS.md`/`CLAUDE.md` |",
    "",
    "#### `pb project list`",
    "",
    "List your server-side projects, marking the one bound here.",
    "",
    "#### `pb project rename <name>`",
    "",
    "Rename the bound project (updates the server when bound).",
    "",
    "#### `pb project delete`",
    "",
    "Delete the bound remote project and unbind. Local files are left in place. `-y`/`--yes`",
    "skips the confirmation prompt.",
    "",
    "#### `pb project unbind`",
    "",
    "Detach the directory from its remote project, keeping both copies.",
    "",
    "### Sync",
    "",
    "#### `pb sync`",
    "",
    "Reconcile with the server: publishes a local project on the first sync (when logged in),",
    "pulls remote changes, re-downloads missing sources, and regenerates `refs.bib` and this",
    "guide. Runs local-only when not logged in.",
    "",
    "Once a project is bound, most in-project commands run this reconcile automatically when they",
    "finish, so local and server stay in step without an explicit `pb sync`. The automatic pass",
    "is quiet (it only speaks up on a real failure), best-effort (a network blip never fails the",
    "command), and only touches **already-bound** projects — a local-only project stays offline",
    "until you publish it with an explicit `pb sync`. Set `PAPERBAKER_NO_SYNC=1` to turn the",
    "automatic pass off.",
    "",
    "### Account",
    "",
    "#### `pb login`",
    "",
    "Sign in via a browser device link. `--open` opens the verification URL automatically.",
    "",
    "#### `pb logout`",
    "",
    "Remove the stored credential.",
    "",
    "#### `pb whoami`",
    "",
    "Print the current authentication status.",
    "",
    "### Maintenance",
    "",
    "#### `pb update`",
    "",
    "Update `pb` to the latest release. `--force` reinstalls even if already current.",
    "",
    "Because `pb` is meant to be driven by coding agents, it also keeps itself current on its",
    "own: after a command (at most once every four hours) it checks for a newer release in the",
    "background and, if there is one, downloads and swaps the binary in place — the running",
    "command never waits, and the next invocation runs the new version and prints a one-line",
    "notice. Turn it off with `pb update --auto off` (persisted) or `PAPERBAKER_NO_UPDATE=1`",
    "(per-invocation); re-enable with `pb update --auto on`.",
    "",
    "Every download — manual or automatic — is verified before it is installed: each release",
    "binary is signed in CI with an Ed25519 key whose public half is compiled into `pb`, and an",
    "update is written only if its signature verifies and the version moves strictly forward, so",
    "a tampered, unsigned, or downgraded binary is rejected with the current install untouched.",
    "",
    "#### `pb uninstall`",
    "",
    "Remove the binary and its `PATH` entries. `--purge` also deletes the stored config;",
    "`--keep-config` keeps it without prompting.",
    "",
    "### Environment",
    "",
    "| Variable | Effect |",
    "| --- | --- |",
    '| `PAPERBAKER_QUIET=1` | Silence the "not signed in" notice (and the auto-update notice) |',
    "| `PAPERBAKER_NO_SYNC=1` | Disable the automatic post-command sync |",
    "| `PAPERBAKER_NO_UPDATE=1` | Disable the background auto-update for this invocation |",
    "| `PAPERBAKER_TOKEN` | Supply a credential for headless/CI use |",
    "| `PAPERBAKER_API_URL` | Override the backend API base URL |",
    "",
    "## The `paperbaker/` directory",
    "",
    "Everything `pb` manages lives in one **visible** `paperbaker/` directory (not a dot-dir), so",
    "agent search tools (ripgrep et al.) can read both the metadata and the paper text.",
    "",
    "```text",
    "your-project/",
    "├── AGENTS.md            # (or CLAUDE.md) short brief pointing agents at the papers",
    "└── paperbaker/",
    "    ├── config.json      # project binding: name, stableId, id, ownerHandle",
    "    ├── papers.json      # manifest: paper list + cached metadata",
    "    ├── refs.bib         # generated BibTeX bibliography",
    "    ├── README.md        # this guide (generated)",
    "    └── sources/         # nested git repo — tex per paper",
    "        └── arxiv-1706.03762/",
    "            ├── *.tex, *.bib, *.bbl",
    "            └── figures/",
    "```",
    "",
    "`config.json`, `papers.json`, `refs.bib`, and `README.md` are meant to be committed — a",
    "teammate or fresh agent reproduces the corpus with one `pb sync`. `sources/` is a sealed",
    "nested git repo so the bulky, re-downloadable tex stays out of your project's history: a",
    "`git add -A` can stage at most a gitlink for it, never the tex files themselves.",
    "",
  ];

  if (papers.length > 0) {
    lines.push("## Papers in this project", "");
    for (const paper of papers) {
      lines.push(`### ${paper.title}`);
      lines.push(`- **ID:** ${paper.paperId}`);
      lines.push(`- **Authors:** ${paper.authors.map((a) => a.name).join(", ")}`);
      lines.push(`- **Date:** ${paper.publishedAt.slice(0, 10)}`);
      lines.push(`- **Source:** \`${SOURCES_REL}/${sourceDirName(paper)}/\``);
      lines.push("");
    }
  }

  return lines.join("\n");
}
